apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore-backend

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: bookstore
  app.kubernetes.io/component: backend
  app.kubernetes.io/managed-by: kustomize
