apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: bookstore-backend
  labels:
    app: bookstore
    component: backend
type: Opaque
stringData:
  DB_HOST: mysql.bookstore-database.svc.cluster.local
  DB_USER: bookstore
  DB_PASSWORD: bookstore123
  DB_NAME: bookstore
  REDIS_HOST: redis.bookstore-database.svc.cluster.local
  REDIS_PORT: "6379"
