apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore-database

resources:
  - namespace.yaml
  - secret.yaml
  - mysql-init-configmap.yaml
  - pvc.yaml
  - mysql-deployment.yaml
  - redis-deployment.yaml

commonLabels:
  app.kubernetes.io/name: bookstore
  app.kubernetes.io/component: database
  app.kubernetes.io/managed-by: kustomize
