apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: bookstore-database
  labels:
    app: bookstore
    component: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_USER: bookstore
  MYSQL_PASSWORD: bookstore123
  DB_USER: bookstore
  DB_PASSWORD: bookstore123
