apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: bookstore-frontend
  labels:
    app: bookstore
    component: frontend
data:
  API_URL: http://backend.bookstore-backend.svc.cluster.local:3000
  NODE_ENV: production
  LOG_LEVEL: info
