apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore-frontend

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: bookstore
  app.kubernetes.io/component: frontend
  app.kubernetes.io/managed-by: kustomize
