apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secret
  namespace: bookstore
  labels:
    app: bookstore
type: Opaque
stringData:
  # MySQL Credentials
  DB_USER: bookstore
  DB_PASSWORD: bookstore123
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_USER: bookstore
  MYSQL_PASSWORD: bookstore123
